version: '3.8'

services:
  db:
    image: mysql
    env_file:
      - ./@libs/prisma-dev/.env
    ports:
      - "3306:3306"
    container_name: mysql-db-shopnest
    volumes:
      - mysql-data-shopnest:/var/lib/mysql

  adminer:
    image: adminer
    ports:
      - 8080:8080
    container_name: adminer-shopnest

  redis-server:
    image: redis
    container_name: redis-server-shopnest
    ports:
      - "6379:6379"
    volumes:
      - redis-data-shopnest:/data

volumes:
  mysql-data-shopnest:
    driver: local
  redis-data-shopnest:
    driver: local
